package controller;

//周五写这个文件： 以下三个方法和主函数（welcome page）。

import java.sql.SQLException;
import myOracle.*;

public abstract class WelcomePage {
    //module 1(1)
    private abstract static class Patron_log_in {

        //module
        public static void main(String[] args) throws Exception { //整体上无重复执行。只进行一次登入。
            //1, hint
            Tools.printModuleIn("Patron_log_in");

            //2, input id -- patron_id, patron
            String patron_id = "";
            PATRON  patron = null;
            int flag = 1;//continue flag
            while (flag == 1) {
                flag = 0;
                patron_id = PATRON.getFromInput_PATRON_ID();
                if (patron_id.equals("*")) { //want to leave
                    System.out.println("Leave patron log in module.");
                    Tools.printLine();
                    return;
                }
                patron = PATRONTable.selectByPATRON_ID(patron_id);
                if (patron == null) { //not find
                    System.out.println("The patron_id is not valid. We cannot find the account in system. Input again or quit.");
                    flag = 1;
//                    Tools.printChooseHint("", "Do you want to input again?", "1-- try again");
//                    flag = Tools.getIntByInput(1);
//                    if (flag == 0) {
//                        System.out.println("Leave patron log in module.");
//                        Tools.printLine();
//                        return;
//                    }
                } else if (!patron.ACTIVITY_STATE){
                    System.out.println("Your account is not activited. Please turn to library staff for help.");
                    System.out.println("Leave patron log in module.");
                    Tools.printLine();
                    return;
                }
            }

            //3, input password. -- get valid password or quit
            String password = "";
            flag = 1;
            int count = 3;
            while (flag == 1 && count > 0) {
                flag = 0;
                password = PATRON.getFromInput_USER_PASSWORD().strip();
                if (password.equals("*")) {
                    System.out.println("Leave patron log in module.");
                    Tools.printLine();
                    return;
                }
                if (! password.equals(patron.USER_PASSWORD.strip())) {
                    count--;
                    System.out.println("Your input is not correct. Input again or quit!");
                    flag = 1;
//                    Tools.printChooseHint("", "Do you want to input again?", "1-- try again");
//                    flag = Tools.getIntByInput(1);
//                    if (flag == 0) {
//                        System.out.println("Leave patron log in module.");
//                        Tools.printLine();
//                        return;
//                    }
                }
            }
            if (count <= 0) {
                System.out.println("Input wrong for 3 times. You are not allowd to log in library system!");
                System.out.println("Leave patron log in module.");
                Tools.printLine();
                return;
            }

            //sccessfully log in.
            PatronPage.main(new String[] {patron_id});
        }
    }



    //module 1(2)
    private abstract static class Patron_sign_up {
        //module
        public static void main(String[] args) throws Exception {
            Tools.printModuleIn("Patron_sign_up");
            System.out.println("Sign up a new library account! \nThe id is generated by the system. You are supposed to enter your information. You can quit or choose to input again during the process.");
            //1, input information -- patron
            PATRON patron = null;
            int flag = 1;
            while (flag == 1) {
                flag = 0;
               patron = PATRON.getFromInput_Instance();

               if (patron == null) {
//                   Tools.printChooseHint("", "Do you want to input again?", "1-- input again");
//                   flag = Tools.getIntByInput(1);

//                   if (flag == 0) {
                       Tools.printModuleOut("patron_sign_up");
                       return;
//                   }
               }
            }
            //
            PATRONTable.insertTuple(patron);
            System.out.println("Sccessfully sign up !");
            Tools.printModuleOut("patron_sign_up");
        }
    }


    //module 1(3)
    private abstract static class Staff_log_in {
        //module
        public static void main(String[] args) throws Exception {
            //1, hint
            Tools.printModuleIn("STAFF_log_in");

            //2, input id -- STAFF_id, STAFF
            String STAFF_id = "";
            STAFF staff = null;
            int flag = 1;//continue flag
            while (flag == 1) {
                flag = 0;
                STAFF_id = STAFF.getFromInput_STAFF_ID();
                if (STAFF_id.equals("*")) { //want to leave
                    System.out.println("Leave STAFF log in module.");
                    Tools.printLine();
                    return;
                }
                staff = STAFFTable.selectBySTAFF_ID(STAFF_id);
                if (staff == null) { //not find
                    System.out.println("The STAFF_id is not valid. We cannot find the account in system. Input again or quit.");
                    flag = 1;
                    //                    Tools.printChooseHint("", "Do you want to input again?", "1-- try again");
//                    flag = Tools.getIntByInput(1);
//                    if (flag == 0) {
//                        System.out.println("Leave STAFF log in module.");
//                        Tools.printLine();
//                        return;
//                    }
                }
            }

            //3, input password. -- get valid password or quit
            String password = "";
            flag = 1;
            int count = 3;
            while (flag == 1 && count > 0) {
                flag = 0;
                password = STAFF.getFromInput_PASSWORD().strip();
                if (password.equals("*")) {
                    System.out.println("Leave STAFF log in module.");
                    Tools.printLine();
                    return;
                }
                if (! password.equals(staff.PASSWORD.strip())) {
                    count--;
                    System.out.println("Your input is not correct. Input again or quit");
                    flag = 1;
//                    Tools.printChooseHint("", "Do you want to input again?", "1-- try again");
//                    flag = Tools.getIntByInput(1);
//                    if (flag == 0) {
//                        System.out.println("Leave STAFF log in module.");
//                        Tools.printLine();
//                        return;
//                    }
                }
            }
            if (count <= 0) {
                System.out.println("Input wrong for 3 times. You are not allowd to log in library system!");
                System.out.println("Leave STAFF log in module.");
                Tools.printLine();
                return;
            }

            //sccessfully log in.
            StaffPage.main(new String[] {STAFF_id});
        }
    }



    //page
    public static void main(String[] args) throws Exception {
    
        while (true) {
            try {
                //1， 等待
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ignored) {
//
//                }
    
                //2， 提示信息。
                System.out.print("\n\n\n\n\n");
                Tools.printELine();
                System.out.println(Tools.welcomePageIn); //in hint (graphical)

                try {
                    Thread.sleep(500);
                } catch (InterruptedException e) {

                }
    
                String description = "";
                String choice = "1--log in as patron / 2--sign up as patron / 3--log in as staff";
                Tools.printChooseHint("", description, choice);
                //3//选择
                int choose = Tools.getIntByInput(3);
                switch (choose) {
                    case 1:
                        //jump over log in process when doing testing! need change back.
//                        String patron_id1 = "64273878p"; //normal process test
//                        String patron_id2 = "21789256p"; //exception case test
//                        PatronPage.main(new String[] {patron_id2});
                        Patron_log_in.main(null);
                        //
                        break;

                    case 2:
                        Patron_sign_up.main(null);
                        break;

                    case 3:
                        //jump over log in process when doing testing! need change back.
//                        String staff_id = "64273878s";
//                        StaffPage.main(new String[] {staff_id});
                        Staff_log_in.main(null);
                        //
                        break;
    
                    default: {
                        System.out.println(Tools.welcomePageOut);
                        return;
                    }
                }
    
            } catch (Exception e) {
//                System.out.println("\nSomething goes wrong in Welcome page.");
//                //供debug使用， 产品发布前删除
//                e.printStackTrace();
                //
            }
        }
    }
}
